cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    gferrettini:
      email: gabriel.ferrettini@irit.fr
      failed_login_attempts: 0
      logged_in: false
      name: Gabriel Ferrettini
      password: $2b$12$LOMvWPYND.hCc5rANCypjuvEPc6o./Jc4SUOQpVz/dRMAP6JqOZwS
pre-authorized:
  emails: null
