cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    gabartas:
      email: gabriel.ferrettini@gmail.com
      logged_in: false
      name: Gabriel Ferrettini
      password: $2b$12$J5QwO2uH1aDYRtA5g9nt8eZOcDHZDLcsGPxRafHLWYnfJaEb2hlM6
    test_student:
      email: gabartas@hotmail.fr
      logged_in: false
      name: tester
      password: $2b$12$BZG99TIzjAj4jj5wU4DeiuQoSACNH.hXc1jsgk07p5MeTo1rC5EGK
pre-authorized:
  emails: null
