credentials:
  usernames:
    gferrettini:
      email: gabriel.ferrettini@irit.fr
      failed_login_attempts: 0 # Will be managed automatically
      name: Gabriel Ferrettini
      password: test_password # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails: